### ISSUE TITLE
Create CI with travis

### ISSUE THREAD

**Issue by josemussa** [josemussa/alexa-connect-handlers#4]
Create release when merge to master.
Publish latest release.
run lint and tests on PR.
run lint, tests, build and release on merge to master.

**Comment by ReDBrother** [comment]
i can handle it

**Comment by josemussa** [comment]
Perfect @ReDBrother 👍 I was planning to use Travis for this, what's the approach you want to follow?

**Comment by ReDBrother** [comment]
Travis ci will launch lint and test npm scripts and i thought about [this](https://docs.travis-ci.com/user/deployment/pages/). almost done
Maybe should synchronize node version in .nvm and .travis.yml files...
